### ISSUE TITLE
startActive was deprecated in opentracing-util 0.32.0 and removed in 0.33.0

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/java-aws-lambda#18]
The [TracingRequestHandler](https://github.com/newrelic/java-aws-lambda/blob/master/src/main/java/com/newrelic/opentracing/aws/TracingRequestHandler.java#L55) and [TracingRequestStreamHandler](https://github.com/newrelic/java-aws-lambda/blob/master/src/main/java/com/newrelic/opentracing/aws/TracingRequestStreamHandler.java#L54) both call `startActive` which was deprecated in opentracing-util 0.32.0 and removed in 0.33.0.

https://github.com/opentracing/opentracing-java/blob/v0.32.0/opentracing-api/src/main/java/io/opentracing/Tracer.java#L262-L263

We should update these handlers to instead use `start` and release a new version that supports opentracing-util 0.33.0 and above.

**Comment by agarbutt** [comment]
I am attempting to leverage this library in a Java Lambda, and I ran into the dependency issue.
See #19 as the documentation needs to be updated at least.

**Comment by jasonjkeller** [comment]
This was address by #29
