### ISSUE TITLE
HeadersParser doesn't recognize APIGatewayV2ProxyResponseEvent

### ISSUE THREAD

**Issue by retnuh** [newrelic/java-aws-lambda#30]
Hi there, looking through the source (evaluating applicability to an upcoming project) I notice that the `ResponseParser` and the `EventSourceParser` both can handle `APIGatewayV2ProxyResponseEvent`, but not the `HeadersParser`.  The `APIGatewayV2ProxyResponseEvent` also has a `getHeaders()` method that seems like it would be appropriate.

**Comment by gfuller1** [comment]
Hello @retnuh ! Apologies for the delayed response. I don't see why we couldn't do that. We are a bit busy at the moment so we can't get to this immediately. If you'd prefer to get it done sooner you could try implementing it and we would gladly give you feedback on it!

**Comment by kford-newrelic** [comment]
Hi @retnuh this is a good suggestion but unfortunately, we won't be able to prioritize this for our roadmap. If you ever have the desire to actually implement this and submit a PR that we can approve and merge, we might be able to find some company swag to send your way! For now though, we'll have to close this with no further action.
